baseURL = 'https://vvvincent.me'
languageCode = 'en-us'
title = 'Vincent Cheng'
theme = "paper"

[pagination]
  pagerSize = 100

# Add this menu section
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  # Add more buttons as needed, for example:
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 30

[params]
  customCSS = ["css/custom.css"]
  
  # Enable math typesetting
  math = true
  
  # Add KaTeX support
  katex = true
  
  # Empty mainSections means nothing shows on homepage
  # mainSections = ["about"]

  twitter = 'vvvincent_c'
  github = 'vncntt'

[permalinks]
  notes = "/:filename/"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
