baseURL = 'https://vvvincent.me'
languageCode = 'en-us'
title = 'Vincent Cheng'
theme = "paper"

[pagination]
  pagerSize = 100

# Add this menu section
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  # Add more buttons as needed, for example:
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 30

[params]
  customCSS = ["css/custom.css"]
  
  # Enable math typesetting
  math = true
  
  # Add KaTeX support
  katex = true
  
  # Empty mainSections means nothing shows on homepage
  # mainSections = ["about"]

  twitter = 'vvvincent_c'
  github = 'vncntt'
  
  # SEO and metadata
  description = "Vincent Cheng, UCSD Math-CS student, Cornell, Atlas fellow, Redwood, METR, Felicis Fellow,  Interested in math, ML, AI, Brazilian Jiu-Jitsu, tennis, learning, and arm-wrestling."
  author = "Vincent Cheng"
  keywords = ["Vincent Cheng", "UCSD", "Cornell", "Math-CS", "Atlas Fellow", "Ross", "WARP", "IOAI", "ML", "AI"]

  images = ["/photo_new.jpg"]
  ogImage = "/photo_new.jpg"

[permalinks]
  notes = "/:filename/"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
